version: "3.9"
services:
  api:
    build: ./api
    container_name: cesizen-api
    ports: ["8080:8080"]
  web:
    build: ./CESIZen_front
    container_name: cesizen-front
    depends_on: [api]
    ports: ["80:80", "443:443"]
